import { minify } from 'html-minifier';

export default null;

export const minifyHtml = () => {
	return {
		name: 'html-transform',
		transformIndexHtml(html: string) {
			return minify(html, {
				collapseBooleanAttributes: true,
				collapseInlineTagWhitespace: false,
				collapseWhitespace: true,
				conservativeCollapse: false,
				continueOnParseError: false,
				includeAutoGeneratedTags: false,
				ignoreCustomComments: [/♀/],
				removeComments: true,
				removeEmptyAttributes: true,
				removeRedundantAttributes: true,
			});
		},
	};
};
