---
name: Prettier
# Runs and writes the results of prettier to changed files
# Only runs when changes happen to main

'on':
    push:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                # Make sure the actual branch is checked out when running on pull requests
                ref: ${{ github.head_ref }}
                # This is important to fetch the changes to the previous commit
                fetch-depth: 0
            - name: prettify
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write **/*.{ts,json,css,scss,md}
                  only_changed: true
                  commit_message: "[chore] prettified code"
